name: Build, Test, Deploy

on:
  push:
    branches:
      - DEVLAB-51/basic-setup

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Initial Build
        run: echo "Hello! Welcome to the build"

      - name: Test RDP Connectivity
        run: |
          echo "Checking RDP port on VM..."
          nc -vz 172.190.99.22 3389

  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Test
        run: echo "Time for a test"

  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy
        run: echo "Test deploy"
